# 2022-05-09 11:57:13
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-05-13 22:43:40
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-05-13 22:43:40
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-01 20:54:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-01 20:54:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-01 20:54:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-01 20:54:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-04 01:01:16
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-04 13:51:49
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-05 01:27:23
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-08 12:44:53
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-09 17:34:00
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-12 18:06:30
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-12 19:48:45
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-12 21:23:08
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-14 03:32:14
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-14 18:54:41
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-16 00:17:39
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-16 03:14:38
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-18 01:55:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-18 01:55:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-18 01:55:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-18 01:55:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-18 01:55:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-18 22:49:33
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-21 14:38:41
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-22 00:53:34
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-22 00:53:34
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-22 00:53:34
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-22 20:01:31
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-23 01:19:42
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-23 03:04:27
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-23 16:05:40
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-25 03:39:02
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-25 19:59:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-26 12:30:23
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 12:31:15
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 12:33:29
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 12:44:29
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 12:44:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 12:46:43
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 14:40:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 14:46:01
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-26 14:46:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-28 22:00:45
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-29 19:49:26
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-30 01:52:13
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-30 22:48:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 924


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-30 23:57:28
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-31 12:38:55
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-31 13:19:22
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-07-31 13:24:42
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-07-31 17:46:15
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-01 01:34:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-02 13:20:40
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-06 10:08:04
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-07 19:49:23
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-08 16:03:20
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-09 01:07:59
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-10 00:52:07
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-11 17:29:26
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-12 14:45:35
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-12 17:30:36
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-13 01:03:40
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-13 04:52:28
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-14 01:16:40
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-14 22:00:01
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-15 00:11:20
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-17 13:27:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-17 13:27:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-17 13:27:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 598


# 2022-08-17 21:40:17
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-18 11:02:23
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-19 00:23:02
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-20 01:45:13
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-23 10:12:32
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-26 01:17:29
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-26 15:51:56
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


# 2022-08-27 01:51:25
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\Kaldenia\Serveur\Server\Network\NetState.cs:ligne 813


